package com.example.generatordemo.mapper;

import com.example.generatordemo.pojo.Coffee;
import com.example.generatordemo.pojo.CoffeeExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface CoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    long countByExample(CoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    int deleteByExample(CoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    @Delete({
            "delete from product",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    @Insert({
            "insert into product (name, price, ",
            "inventory, is_Virtual, ",
            "del_flag)",
            "values (#{name,jdbcType=VARCHAR}, #{money,jdbcType=BIGINT,typeHandler=com.example.generatordemo.handler.MoneyTypeHandler}, ",
            "#{inventory,jdbcType=BIGINT}, #{isVirtual,jdbcType=INTEGER}, ",
            "#{delFlag,jdbcType=INTEGER})"
    })
    @SelectKey(statement = "CALL IDENTITY()", keyProperty = "id", before = false, resultType = Integer.class)
    int insert(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    int insertSelective(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    List<Coffee> selectByExampleWithRowbounds(CoffeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    List<Coffee> selectByExample(CoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    @Select({
            "select",
            "id, name, price, inventory, is_Virtual, del_flag",
            "from product",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.generatordemo.mapper.CoffeeMapper.BaseResultMap")
    Coffee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") Coffee record, @Param("example") CoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    int updateByExample(@Param("record") Coffee record, @Param("example") CoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    int updateByPrimaryKeySelective(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    @Update({
            "update product",
            "set name = #{name,jdbcType=VARCHAR},",
            "price = #{money,jdbcType=BIGINT,typeHandler=com.example.generatordemo.handler.MoneyTypeHandler},",
            "inventory = #{inventory,jdbcType=BIGINT},",
            "is_Virtual = #{isVirtual,jdbcType=INTEGER},",
            "del_flag = #{delFlag,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Coffee record);
}