package com.example.generatordemo.pojo;

import java.io.Serializable;
import java.util.Date;

public class Coffee implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MENU.ID
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MENU.NAME
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MENU.PRICE
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MENU.CREATE_TIME
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MENU.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MENU
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MENU.ID
     *
     * @return the value of T_MENU.ID
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MENU.ID
     *
     * @param id the value for T_MENU.ID
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MENU.NAME
     *
     * @return the value of T_MENU.NAME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MENU.NAME
     *
     * @param name the value for T_MENU.NAME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MENU.PRICE
     *
     * @return the value of T_MENU.PRICE
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MENU.PRICE
     *
     * @param price the value for T_MENU.PRICE
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MENU.CREATE_TIME
     *
     * @return the value of T_MENU.CREATE_TIME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MENU.CREATE_TIME
     *
     * @param createTime the value for T_MENU.CREATE_TIME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MENU.UPDATE_TIME
     *
     * @return the value of T_MENU.UPDATE_TIME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MENU.UPDATE_TIME
     *
     * @param updateTime the value for T_MENU.UPDATE_TIME
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MENU
     *
     * @mbggenerated Fri Apr 26 15:11:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}