package com.example.generatordemo.pojo;

import java.io.Serializable;

import org.joda.money.Money;

public class Coffee implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private Money money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inventory
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private Long inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_Virtual
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private Integer isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.del_flag
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public Money getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param money the value for product.price
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setMoney(Money money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inventory
     *
     * @return the value of product.inventory
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public Long getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inventory
     *
     * @param inventory the value for product.inventory
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setInventory(Long inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_Virtual
     *
     * @return the value of product.is_Virtual
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public Integer getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_Virtual
     *
     * @param isVirtual the value for product.is_Virtual
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setIsVirtual(Integer isVirtual) {
        this.isVirtual = isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.del_flag
     *
     * @return the value of product.del_flag
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.del_flag
     *
     * @param delFlag the value for product.del_flag
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 26 15:39:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", money=").append(money);
        sb.append(", inventory=").append(inventory);
        sb.append(", isVirtual=").append(isVirtual);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}